FROM node:22 As build

WORKDIR /app

COPY package.json  package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.29.3-alpine AS production

COPY --from=build /app/nginx /etc/nginx/conf.d

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]